server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: springBootGroup
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
         spring.json.trusted.packages: '*'
